### ISSUE TITLE
Wrap the giant text selector in :where?

### ISSUE THREAD

**Issue by dbox** [kni-labs/kni-scss#44]
Might make it easier to overwrite, but not sure it matters much

**Comment by dbox** [comment]
I think this is it...

```css
// set global absolute minimum clamp to 10
  --fontSizeMin: max(10, calc(var(--fontSize) * var(--siteMin) / var(--siteBasis)));
  --fontSizeMax: calc(var(--fontSize) * var(--siteMax) / var(--siteBasis));
}

:where(tt, i, b, big, small, em, strong, dfn, code, samp, kbd, var, cite, abbr, acronym, sub, sup, span, bdo, address, div, a, object, p, h1, h2, h3, h4, h5, h6, pre, q, ins, del, dt, dd, li, label, option, textarea, fieldset, legend, button, caption, td, th, title, blockquote, time, input) {
  font-size: clamp(
    var(--fontSizeMin),
    calc((var(--fontSizeMin) / var(--emBase)) * 1rem + (var(--fontSizeMax) - var(--fontSizeMin)) * (100vw - var(--siteMin) * 1px) / (var(--siteMax) - var(--siteMin))),
    var(--fontSizeMax)
  );
}
```
